# Generated by Django 5.1.6 on 2025-03-10 04:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServicePlatform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('google', 'Google Reviews'), ('facebook', 'Facebook Page Reviews')], max_length=50, unique=True)),
                ('platform_credentials', models.JSONField(default=dict)),
                ('service_provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Service Platform',
                'verbose_name_plural': 'Service Platforms',
            },
        ),
    ]
