# Generated by Django 5.1.6 on 2025-03-10 04:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_serviceplatform'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='google_place_id',
        ),
    ]
