# Generated by Django 5.1.6 on 2025-03-10 05:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_customuser_google_place_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ServicePlatform',
        ),
    ]
