# Generated by Django 5.1.6 on 2025-03-11 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_platform', '0002_customer_alter_serviceplatforms_credentials_campaign'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='is_given_review',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customer',
            name='is_sent_email',
            field=models.BooleanField(default=False),
        ),
        migrations.RemoveField(
            model_name='campaign',
            name='customer',
        ),
        migrations.AddField(
            model_name='campaign',
            name='customer',
            field=models.ManyToManyField(to='service_platform.customer'),
        ),
    ]
