# Generated by Django 5.1.6 on 2025-03-10 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_platform', '0002_alter_googlereviewplatform_service_provider'),
    ]

    operations = [
        migrations.AddField(
            model_name='googlereviewplatform',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
