# Generated by Django 5.1.6 on 2025-03-10 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service_platform', '0003_googlereviewplatform_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GoogleReviewPlatform',
        ),
    ]
