# Generated by Django 5.1.6 on 2025-03-11 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_platform', '0004_remove_campaign_customer_customer_campaign'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='campaign',
            field=models.ManyToManyField(related_name='customers', to='service_platform.campaign'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
