# Generated by Django 5.1.7 on 2025-03-17 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_platform', '0006_campaign_communication_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='is_send_sms',
            field=models.BooleanField(default=False),
        ),
    ]
