# Generated by Django 5.1.7 on 2025-03-17 05:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service_platform', '0007_customer_is_send_sms'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='is_send_sms',
            new_name='is_sent_sms',
        ),
    ]
