# Generated by Django 5.1.7 on 2025-03-19 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_platform', '0008_rename_is_send_sms_customer_is_sent_sms'),
    ]

    operations = [
        migrations.CreateModel(
            name='CampaignMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(blank=True, max_length=255, null=True)),
                ('message', models.TextField()),
                ('communication_type', models.CharField(choices=[('Email', 'Email'), ('SMS', 'SMS'), ('WhatsApp', 'WhatsApp')], max_length=10)),
            ],
        ),
    ]
