# Generated by Django 5.1.7 on 2025-03-20 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_platform', '0009_campaignmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='platform',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='platform',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='platforms/'),
        ),
        migrations.AddField(
            model_name='platform',
            name='platform_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
