# Generated by Django 5.1.7 on 2025-05-05 11:19

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_platform', '0013_emaillog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='serviceplatforms',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='customer',
            name='slug',
        ),
        migrations.AddField(
            model_name='customer',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, null=True),
        ),
        migrations.RemoveField(
            model_name='customer',
            name='campaign',
        ),
        migrations.AlterField(
            model_name='customerreview',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='service_platform.customer'),
        ),
        migrations.AlterField(
            model_name='customerreview',
            name='rating',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AddConstraint(
            model_name='serviceplatforms',
            constraint=models.UniqueConstraint(fields=('service_provider', 'platform'), name='unique_service_platform'),
        ),
        migrations.AddField(
            model_name='customer',
            name='campaign',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='customers', to='service_platform.campaign'),
            preserve_default=False,
        ),
    ]
