# Generated by Django 5.1.7 on 2025-04-30 09:37

import django.core.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_platform', '0013_emaillog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='serviceplatforms',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='customerreview',
            name='rating',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AddConstraint(
            model_name='serviceplatforms',
            constraint=models.UniqueConstraint(fields=('service_provider', 'platform'), name='unique_service_platform'),
        ),
    ]
