# Generated by Django 5.1.7 on 2025-05-07 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_platform', '0014_alter_serviceplatforms_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serviceplatforms',
            name='credentials',
        ),
        migrations.AddField(
            model_name='serviceplatforms',
            name='platform_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
