# Generated by Django 5.1.7 on 2025-05-09 12:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_platform', '0015_remove_serviceplatforms_credentials_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OnlineReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reviewer', models.CharField(blank=True, max_length=200, null=True)),
                ('review', models.TextField(blank=True, null=True)),
                ('review_date', models.DateField()),
                ('reviewer_image', models.URLField(blank=True, null=True)),
                ('rating', models.IntegerField(blank=True, null=True)),
                ('service_provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service_platform.serviceplatforms')),
            ],
        ),
    ]
