# Generated by Django 5.1.7 on 2025-05-12 06:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service_platform', '0016_onlinereview'),
    ]

    operations = [
        migrations.RenameField(
            model_name='onlinereview',
            old_name='service_provider',
            new_name='service_platform',
        ),
    ]
