# Generated by Django 5.1.7 on 2025-05-12 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_platform', '0017_rename_service_provider_onlinereview_service_platform'),
    ]

    operations = [
        migrations.AddField(
            model_name='onlinereview',
            name='review_id',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
    ]
