# Generated by Django 5.1.7 on 2025-05-15 04:54

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_platform', '0019_alter_customerreview_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='uuid',
            field=models.UUIDField(blank=True, default=uuid.uuid4, editable=False, null=True),
        ),
    ]
