# Generated by Django 5.1.7 on 2025-05-15 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_platform', '0021_campaign_end_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
