# Generated by Django 5.1.7 on 2025-05-15 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_platform', '0022_campaign_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onlinereview',
            name='reviewer_image',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
